server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-shopping-batch
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:}/${MYSQL_NAME}?serverTimezone=UTC
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false # not execute on starting application
    jdbc:
      initialize-schema: "always"

fpt:
  host: ${FTP_HOST}
  user: ${FTP_USER}
  pass: ${FTP_PASS}
  port: ${FTP_PORT}
